export function getTranslatedCategories(t) {
  return [
    {
      name: t("Categories.Music.Title"),
      image: "/music.jpg",
      description: t("Categories.Music.Description"),
      alt: t("Categories.Music.Alt"),
      fileNameBackEnd: t("Categories.Music.FileNameBackEnd"),
      backendsync: "Music",
      number: 1,
    },
    {
      name: t("Categories.SportAndLeisure.Title"),
      image: "/sport_and_leisure.jpg",
      description: t("Categories.SportAndLeisure.Description"),
      alt: t("Categories.SportAndLeisure.Alt"),
      fileNameBackEnd: t("Categories.SportAndLeisure.FileNameBackEnd"),
      backendsync: "SportAndLeisure",
      number: 2,
    },
    {
      name: t("Categories.FilmAndTV.Title"),
      image: "/film_and_tv.jpg",
      description: t("Categories.FilmAndTV.Description"),
      alt: t("Categories.FilmAndTV.Alt"),
      fileNameBackEnd: t("Categories.FilmAndTV.FileNameBackEnd"),
      backendsync: "FilmAndTV",
      number: 3,
    },
    {
      name: t("Categories.ArtsAndLiterature.Title"),
      image: "/arts_and_literature.jpg",
      description: t("Categories.ArtsAndLiterature.Description"),
      alt: t("Categories.ArtsAndLiterature.Alt"),
      fileNameBackEnd: t("Categories.ArtsAndLiterature.FileNameBackEnd"),
      backendsync: "ArtsAndLiterature",
      number: 4,
    },
    {
      name: t("Categories.History.Title"),
      image: "/history.jpg",
      description: t("Categories.History.Description"),
      alt: t("Categories.History.Alt"),
      fileNameBackEnd: t("Categories.History.FileNameBackEnd"),
      backendsync: "History",
      number: 5,
    },
    {
      name: t("Categories.SocietyAndCulture.Title"),
      image: "/society_and_culture.jpg",
      description: t("Categories.SocietyAndCulture.Description"),
      alt: t("Categories.SocietyAndCulture.Alt"),
      fileNameBackEnd: t("Categories.SocietyAndCulture.FileNameBackEnd"),
      backendsync: "SocietyAndCulture",
      number: 6,
    },
    {
      name: t("Categories.Science.Title"),
      image: "/science.jpg",
      description: t("Categories.Science.Description"),
      alt: t("Categories.Science.Alt"),
      fileNameBackEnd: t("Categories.Science.FileNameBackEnd"),
      backendsync: "Science",
      number: 7,
    },
    {
      name: t("Categories.Geography.Title"),
      image: "/geography.jpg",
      description: t("Categories.Geography.Description"),
      alt: t("Categories.Geography.Alt"),
      fileNameBackEnd: t("Categories.Geography.FileNameBackEnd"),
      backendsync: "Geography",
      number: 8,
    },
    {
      name: t("Categories.FoodAndDrink.Title"),
      image: "/food_and_drink.jpg",
      description: t("Categories.FoodAndDrink.Description"),
      alt: t("Categories.FoodAndDrink.Alt"),
      fileNameBackEnd: t("Categories.FoodAndDrink.FileNameBackEnd"),
      backendsync: "FoodAndDrink",
      number: 9,
    },
    {
      name: t("Categories.GeneralKnowledge.Title"),
      image: "/general_knowledge.jpg",
      description: t("Categories.GeneralKnowledge.Description"),
      alt: t("Categories.GeneralKnowledge.Alt"),
      fileNameBackEnd: t("Categories.GeneralKnowledge.FileNameBackEnd"),
      backendsync: "GeneralKnowledge",
      number: 10,
    },
  ];
}